language: node_js
node_js:
  - 12.12.0
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
env:
  matrix:
    - REACT_APP_YOWTF="WHYISTHISONEWORKING"
    - REACT_APP_API_KEYYO=$API_KEYYO
