language: node_js
node_js:
  - 12.12.0
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run test:coveralls
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
